package com.group7.generators

import com.group7.properties.DisplayProperty
import com.group7.properties.FieldDisplayProperty
import com.group7.properties.GroupDisplayProperty
import com.group7.utils.RandomContext
import com.group7.utils.suffix
import com.group7.utils.toStringWithBestUnit
import kotlin.time.Duration
import kotlin.time.DurationUnit
import kotlin.time.toDuration
import umontreal.ssj.randvar.ExponentialGen
import umontreal.ssj.randvar.GammaGen
import umontreal.ssj.randvar.NormalGen
import umontreal.ssj.rng.MRG32k3a

/**
 * Generates an infinite iterator over instances `T` and delays between their emissions by a node that generates
 * traffic, i.e., [com.group7.nodes.ArrivalNode].
 *
 * Generators can then be truncated with `.take(n)` for a finite iterator.
 */
interface Generator<out T> : Iterator<Pair<T, Duration>> {
    val displayProperty: DisplayProperty
}

/**
 * Provides a delay between emissions for the a [Generator] timetable
 *
 * @property nextDelay Samples the object for the duration to the next emission by the Generator.
 */
interface DelayProvider {
    fun nextDelay(): Duration

    val displayProperty: DisplayProperty

    companion object {
        operator fun invoke(displayProperty: DisplayProperty, block: () -> Duration): DelayProvider =
            object : DelayProvider {
                override val displayProperty: DisplayProperty
                    get() = displayProperty

                override fun nextDelay(): Duration = block()
            }
    }
}

/** Default generators */
object Generators {
    /**
     * A generator that emits only one type of entity at an interval.
     *
     * @param factory Generates instances of the entity
     * @param delayProvider [DelayProvider] to sample delays between emissions from
     */
    fun <T> constant(factory: () -> T, delayProvider: DelayProvider): Generator<T> =
        generateSequence { factory() to delayProvider.nextDelay() }.asGenerator(delayProvider.displayProperty)

    /**
     * Alternates between entities generated by `vararg objs` at an interval.
     *
     * @param factories Multiple factories that generate instances of an entity when invoked.
     * @param delayProvider [DelayProvider] to sample delays between emissions from.
     */
    fun <T> alternating(vararg factories: () -> T, delayProvider: DelayProvider): Generator<T> =
        generateSequence { factories.map { it() } }
            .flatten()
            .map { it to delayProvider.nextDelay() }
            .asGenerator(delayProvider.displayProperty)
}

/** Default delays */
object Delays {
    /**
     * Fixed time delay
     *
     * @param delay Duration delay between events
     */
    fun fixed(delay: Duration): DelayProvider {
        val displayProperty =
            GroupDisplayProperty(
                "Fixed Delay Provider Parameters",
                FieldDisplayProperty("Delay", delay.toStringWithBestUnit()),
            )
        return DelayProvider(displayProperty) { delay }
    }

    /**
     * Samples an exponential distribution for the time delay
     *
     * @param lambda Number of events per time unit specified
     * @param unit [DurationUnit] such that on average `lambda` number of events happens per `unit`
     */
    fun exponential(lambda: Double, unit: DurationUnit): DelayProvider {
        val stream = MRG32k3a() // Random number stream to take from
        stream.setSeed(LongArray(6) { RandomContext.nextLong().toInt().toLong() })

        val expGen = ExponentialGen(stream, lambda) // exponential distribution
        val displayProperty =
            GroupDisplayProperty(
                "Exponential Delay Provider",
                FieldDisplayProperty("lambda", "${"%.2f".format(lambda)}${unit.suffix}"),
            )
        return DelayProvider(displayProperty) { expGen.nextDouble().toDuration(unit) }
    }

    /**
     * Samples an exponential distribution for the time delay
     *
     * @param mean Average delay between events happening
     */
    fun exponentialWithMean(mean: Duration): DelayProvider {
        val displayProperty =
            GroupDisplayProperty(
                "Exponential Delay Provider",
                FieldDisplayProperty("Mean", mean.toStringWithBestUnit()),
            )
        val exp = exponential(1 / mean.toDouble(DurationUnit.SECONDS), DurationUnit.SECONDS)
        return DelayProvider(displayProperty, { exp.nextDelay() })
    }

    /**
     * Samples a normal (Gaussian) distribution for the time delay. Negative samples are clamped to zero.
     *
     * @param mean Mean delay between events
     * @param stdDev Standard deviation of the delay
     * @param unit Optional [DurationUnit] for display formatting; if null, best unit is chosen automatically
     */
    fun normal(mean: Duration, stdDev: Duration, unit: DurationUnit? = null): DelayProvider {
        val stream = MRG32k3a()
        stream.setSeed(LongArray(6) { RandomContext.nextLong().toInt().toLong() })

        val internalUnit = unit ?: DurationUnit.SECONDS
        val normalGen = NormalGen(stream, mean.toDouble(internalUnit), stdDev.toDouble(internalUnit))
        val displayProperty =
            GroupDisplayProperty(
                "Normal Delay Provider",
                FieldDisplayProperty(
                    "Mean",
                    unit?.let { "${"%.2f".format(mean.toDouble(it))}${it.suffix}" } ?: mean.toStringWithBestUnit(),
                ),
                FieldDisplayProperty(
                    "Std Dev",
                    unit?.let { "${"%.2f".format(stdDev.toDouble(it))}${it.suffix}" } ?: stdDev.toStringWithBestUnit(),
                ),
            )
        return DelayProvider(displayProperty) { normalGen.nextDouble().coerceAtLeast(0.0).toDuration(internalUnit) }
    }

    /**
     * Samples a gamma distribution for the time delay.
     *
     * @param mean Mean delay between events
     * @param stdDev Standard deviation of the delay
     * @param unit Optional [DurationUnit] for display formatting; if null, best unit is chosen automatically
     */
    fun gamma(mean: Duration, stdDev: Duration, unit: DurationUnit? = null): DelayProvider {
        val stream = MRG32k3a()
        stream.setSeed(LongArray(6) { RandomContext.nextLong().toInt().toLong() })

        val internalUnit = unit ?: DurationUnit.SECONDS
        val meanVal = mean.toDouble(internalUnit)
        val stdDevVal = stdDev.toDouble(internalUnit)
        val alpha = (meanVal * meanVal) / (stdDevVal * stdDevVal)
        val beta = meanVal / (stdDevVal * stdDevVal)
        val gammaGen = GammaGen(stream, alpha, beta)
        val displayProperty =
            GroupDisplayProperty(
                "Gamma Delay Provider",
                FieldDisplayProperty(
                    "Mean",
                    unit?.let { "${"%.2f".format(meanVal)}${it.suffix}" } ?: mean.toStringWithBestUnit(),
                ),
                FieldDisplayProperty(
                    "Std Dev",
                    unit?.let { "${"%.2f".format(stdDevVal)}${it.suffix}" } ?: stdDev.toStringWithBestUnit(),
                ),
            )
        return DelayProvider(displayProperty) { gammaGen.nextDouble().toDuration(internalUnit) }
    }
}

/**
 * Constraints the generator to only emit a limited number of entities.
 *
 * @param n Number of entities to generate by the generator.
 */
fun <T> Generator<T>.take(n: Int) = asSequence().take(n).asGenerator()

/** Converts a sequence into a generator */
internal fun <T> Sequence<Pair<T, Duration>>.asGenerator(
    displayProperty: DisplayProperty = GroupDisplayProperty("No generator display properties provided")
): Generator<T> =
    object : Generator<T>, Iterator<Pair<T, Duration>> by iterator() {
        override val displayProperty: DisplayProperty
            get() = displayProperty
    }
