package com.group7.utils

import kotlin.contracts.InvocationKind
import kotlin.contracts.contract
import kotlin.random.Random

/** Controls and provides seeds for distributions we sample data from during the running of a scenario. */
object RandomContext {
    private val _metaRandom = ThreadLocal.withInitial { Random(System.nanoTime()) }

    @PublishedApi
    internal var metaRandom
        get() = _metaRandom.get()
        set(value) = _metaRandom.set(value)

    /** Returns an RNG controlled by the RandomContext */
    fun newRandom() = Random(nextLong())

    /** Returns a Long generated by the RandomContext */
    fun nextLong() = metaRandom.nextLong()

    /**
     * Runs block with RandomContext set to specified seed.
     *
     * Resets the seed after the block has been ran.
     *
     * @param seed the seed for RandomContext, which controls all distributions sampled within the block
     * @param block code to run while RandomContext is set to the specified seed
     */
    inline fun <T> withSeed(seed: Long, block: () -> T): T {
        contract { callsInPlace(block, InvocationKind.EXACTLY_ONCE) }

        val oldRandom = metaRandom
        metaRandom = Random(seed)
        try {
            return block()
        } finally {
            metaRandom = oldRandom
        }
    }
}
