package com.group7.dsl

import com.group7.channels.ChannelType
import com.group7.generators.DelayProvider
import com.group7.generators.Generator
import com.group7.nodes.*
import com.group7.nodes.forks.PullForkNode
import com.group7.nodes.forks.PushForkNode
import com.group7.nodes.joins.PullJoinNode
import com.group7.nodes.joins.PushJoinNode
import com.group7.policies.fork.ForkPolicy
import com.group7.policies.generic_fj.FirstAvailablePolicy
import com.group7.policies.generic_fj.RandomPolicy
import com.group7.policies.generic_fj.forkPolicy
import com.group7.policies.generic_fj.joinPolicy
import com.group7.policies.join.JoinPolicy
import com.group7.policies.queue.FIFOQueuePolicy
import com.group7.policies.queue.QueuePolicy
import kotlin.contracts.contract

/**
 * Starts the builder chain, from which more nodes can be attached using the DSL. Vehicles generated by the arrivals
 * node will be pushed to the next node in the chain.
 *
 * Note that if the network cannot support the traffic generated by this arrivals node, the simulation crashes, as this
 * node does not support backpressure.
 *
 * @param generator Generates the vehicles which are inserted into the network by this node.
 */
context(_: ScenarioBuilderScope)
fun <T> arrivals(label: String, generator: Generator<T>): RegularNodeBuilder<ArrivalNode<T>, T, ChannelType.Push> =
    sourceBuilder(ChannelType.Push) { ArrivalNode(label, it, generator) }

/**
 * Starts the builder chain, from which more nodes can be attached using the DSL. Vehicles generated by the arrivals
 * node will be pushed to the next node in the chain.
 *
 * If the network cannot support the traffic generated by this arrivals node, traffic would be lost and counted in a
 * dedicated sink node.
 *
 * @param generator Generates the vehicles which are inserted into the network by this node.
 */
context(_: ScenarioBuilderScope)
fun <T> arrivalsWithLoss(label: String, generator: Generator<T>): NodeBuilder<T, ChannelType.Push> {
    lateinit var output: NodeBuilder<T, ChannelType.Push>
    arrivals(label, generator)
        .thenFork(
            "$label loss fork",
            listOf({ lane1 -> output = lane1 }, { lane2 -> lane2.thenLossSink("$label loss sink") }),
            policy = forkPolicy(FirstAvailablePolicy()),
        )
    return output
}

/**
 * Attaches a delay node to the builder chain, applying a delay to all vehicles passing through the node. Vehicles that
 * has passed through the delay node are pushed to the next node in the chain.
 */
fun <T> NodeBuilder<T, *>.thenDelay(
    label: String,
    delayProvider: DelayProvider,
): RegularNodeBuilder<DelayNode<T>, T, ChannelType.Push> =
    asPush().then(ChannelType.Push) { input, output -> DelayNode(label, input, output, delayProvider) }

/**
 * Attaches a pump node to the builder chain, converting the builder chain from a pull output to a push output.
 *
 * Pump nodes are useful to connect a queue node with another node that requires an push input connection. Pump nodes do
 * not store any items.
 */
fun <T> NodeBuilder<T, ChannelType.Pull>.thenPump(
    label: String = "Pump"
): RegularNodeBuilder<PumpNode<T>, T, ChannelType.Push> =
    then(ChannelType.Push) { input, output -> PumpNode(label, input, output) }

/**
 * Attaches a fork node to the builder chain, which splits the current builder chain to `numLanes` parallel lanes, whose
 * behaviour is determined by `laneAction`. The subsequent lanes will commence with a push input connection from the
 * fork.
 *
 * When used in combination of other nodes, could construct (for example):
 * - with Join -> parallel lanes for traffic to flow through / different paths for different types of port vehicles
 * - with PushConnection -> lane for traffic to head to a previous point in the network, or to join a different network
 *   entirely.
 *
 * @param lanes List of DSL node builder chains to follow, each starting with a pull output connection from this fork
 *   node. [Read more here.](https://simport.xhirp.com/docs/tutorials/03-more-complex-port-layout.html)
 * @param policy How the fork node will decide which lane to push traffic to, when the upstream node pushes traffic into
 *   us
 */
fun <ItemT, R> NodeBuilder<ItemT, ChannelType.Push>.thenFork(
    label: String,
    lanes: List<(RegularNodeBuilder<PushForkNode<ItemT>, ItemT, ChannelType.Push>) -> R>,
    policy: ForkPolicy<ItemT> = forkPolicy(RandomPolicy()),
): List<R> {
    return thenDiverge(ChannelType.Push, lanes.size) { input, outputs -> PushForkNode(label, input, outputs, policy) }
        .zip(lanes) { node, lane -> lane(node) }
}

/**
 * Attaches a fork node to the builder chain, which splits the current builder chain to `numLanes` parallel lanes, whose
 * behaviour is determined by `laneAction`. The subsequent lanes will commence with a push input connection from the
 * fork.
 *
 * When used in combination of other nodes, could construct (for example):
 * - with Join -> parallel lanes for traffic to flow through / different paths for different types of port vehicles
 * - with PushConnection -> lane for traffic to head to a previous point in the network, or to join a different network
 *   entirely.
 *
 * @param numLanes The number of lanes to construct with the provided `laneAction` function
 * @param policy How the fork node will decide which lane to push traffic to, when the upstream node pushes traffic into
 *   us
 * @param laneAction Function that determines the contents of each lane, depending on the lane number.
 *   [Read more here.](https://simport.xhirp.com/docs/tutorials/03-more-complex-port-layout.html)
 */
fun <ItemT, R> NodeBuilder<ItemT, ChannelType.Push>.thenFork(
    label: String,
    numLanes: Int,
    policy: ForkPolicy<ItemT> = forkPolicy(RandomPolicy()),
    laneAction: (Int, RegularNodeBuilder<PushForkNode<ItemT>, ItemT, ChannelType.Push>) -> R,
): List<R> = thenFork(label, List(numLanes) { i -> { node -> laneAction(i, node) } }, policy)

/**
 * Attaches a fork node to the builder chain, which splits the current builder chain to `numLanes` parallel lanes, whose
 * behaviour is determined by `laneAction`. The subsequent lanes will commence with a pull input connection from the
 * fork.
 *
 * When used in combination of other nodes, could construct (for example):
 * - with Join -> parallel lanes for traffic to flow through / different paths for different types of port vehicles
 * - with PushConnection -> lane for traffic to head to a previous point in the network, or to join a different network
 *   entirely.
 *
 * @param lanes List of DSL node builder chains to follow, each starting with a pull output connection from this fork
 *   node. [Read more here.](https://simport.xhirp.com/docs/tutorials/03-more-complex-port-layout.html)
 */
fun <ItemT, R> NodeBuilder<ItemT, ChannelType.Pull>.thenFork(
    label: String,
    lanes: List<(RegularNodeBuilder<PullForkNode<ItemT>, ItemT, ChannelType.Pull>) -> R>,
): List<R> {
    return thenDiverge(ChannelType.Pull, lanes.size) { input, outputs -> PullForkNode(label, input, outputs) }
        .zip(lanes) { node, lane -> lane(node) }
}

/**
 * Attaches a fork node to the builder chain, which splits the current builder chain to `numLanes` parallel lanes, whose
 * behaviour is determined by `laneAction`. The subsequent lanes will commence with a pull input connection from the
 * fork.
 *
 * When used in combination of other nodes, could construct (for example):
 * - with Join -> parallel lanes for traffic to flow through / different paths for different types of port vehicles
 * - with PushConnection -> lane for traffic to head to a previous point in the network, or to join a different network
 *   entirely.
 *
 * @param numLanes The number of lanes to construct with the provided `laneAction` function
 * @param laneAction Function that determines the contents of each lane, depending on the lane number.
 *   [Read more here.](https://simport.xhirp.com/docs/tutorials/03-more-complex-port-layout.html)
 */
fun <ItemT, R> NodeBuilder<ItemT, ChannelType.Pull>.thenFork(
    label: String,
    numLanes: Int,
    laneAction: (Int, RegularNodeBuilder<PullForkNode<ItemT>, ItemT, ChannelType.Pull>) -> R,
): List<R> = thenFork(label, List(numLanes) { i -> { node -> laneAction(i, node) } })

/**
 * Attaches a fork node to the builder chain, which splits the current builder chain to `numLanes` parallel lanes, whose
 * behaviour is determined by `laneAction`. The subsequent lanes will commence with a push input connection from the
 * fork.
 *
 * When used in combination of other nodes, could construct (for example):
 * - with Join -> parallel lanes for traffic to flow through / different paths for different types of port vehicles
 * - with PushConnection -> lane for traffic to head to a previous point in the network, or to join a different network
 *   entirely.
 *
 * @param lanes List of DSL node builder chains to follow, each starting with a pull output connection from this fork
 *   node. [Read more here.](https://simport.xhirp.com/docs/tutorials/03-more-complex-port-layout.html)
 * @param policy How the fork node will decide which lane to push traffic to, when the upstream node pushes traffic into
 *   us
 */
fun <ItemT, R> NodeBuilder<ItemT, *>.thenPushFork(
    label: String,
    lanes: List<(RegularNodeBuilder<PushForkNode<ItemT>, ItemT, ChannelType.Push>) -> R>,
    policy: ForkPolicy<ItemT> = forkPolicy(RandomPolicy()),
): List<R> = asPush().thenFork(label, lanes, policy)

/**
 * Attaches a fork node to the builder chain, which splits the current builder chain to `numLanes` parallel lanes, whose
 * behaviour is determined by `laneAction`. The subsequent lanes will commence with a push input connection from the
 * fork.
 *
 * When used in combination of other nodes, could construct (for example):
 * - with Join -> parallel lanes for traffic to flow through / different paths for different types of port vehicles
 * - with PushConnection -> lane for traffic to head to a previous point in the network, or to join a different network
 *   entirely.
 *
 * @param numLanes The number of lanes to construct with the provided `laneAction` function
 * @param policy How the fork node will decide which lane to push traffic to, when the upstream node pushes traffic into
 *   us
 * @param laneAction Function that determines the contents of each lane, depending on the lane number.
 *   [Read more here.](https://simport.xhirp.com/docs/tutorials/03-more-complex-port-layout.html)
 */
fun <ItemT, R> NodeBuilder<ItemT, *>.thenPushFork(
    label: String,
    numLanes: Int,
    policy: ForkPolicy<ItemT> = forkPolicy(RandomPolicy()),
    laneAction: (Int, RegularNodeBuilder<PushForkNode<ItemT>, ItemT, ChannelType.Push>) -> R,
): List<R> = asPush().thenFork(label, List(numLanes) { i -> { node -> laneAction(i, node) } }, policy)

/**
 * Attaches a join node to the builder chain to join together a list of builder chains (with push output connections).
 * The subsequent connection out of the join node will be a push connection.
 *
 * When used in combination of other nodes, could construct (for example):
 * - following Fork -> parallel lanes for traffic to flow through / different paths for different types of port vehicles
 * - from a list of generators -> mixed arrivals of vehicle of different types
 */
fun <T> List<NodeBuilder<T, ChannelType.Push>>.thenJoin(
    label: String
): RegularNodeBuilder<PushJoinNode<T>, T, ChannelType.Push> =
    thenConverge(ChannelType.Push) { inputs, output -> PushJoinNode(label, inputs, output) }

/**
 * Attaches a join node to the builder chain to join together a list of builder chains (with pull output connections).
 * The subsequent connection out of the join node will be a pull connection.
 *
 * When used in combination of other nodes, could construct (for example):
 * - following Fork -> parallel lanes for traffic to flow through / different paths for different types of port vehicles
 * - from a list of generators -> mixed arrivals of vehicle of different types
 *
 * @param policy How the pull join node will decide which lane to accept vehicles from when the downstream node is pulls
 */
fun <T> List<NodeBuilder<T, ChannelType.Pull>>.thenJoin(
    label: String,
    policy: JoinPolicy<T> = joinPolicy(RandomPolicy()),
): RegularNodeBuilder<PullJoinNode<T>, T, ChannelType.Pull> =
    thenConverge(ChannelType.Pull) { inputs, output -> PullJoinNode(label, inputs, output, policy) }

/**
 * Attaches a join node to the builder chain to join together a list of builder chains. The subsequent connection out of
 * the join node will be a push connection.
 *
 * When used in combination of other nodes, could construct (for example):
 * - following Fork -> parallel lanes for traffic to flow through / different paths for different types of port vehicles
 * - from a list of generators -> mixed arrivals of vehicle of different types
 */
fun <T> List<NodeBuilder<T, *>>.thenPushJoin(label: String): RegularNodeBuilder<PushJoinNode<T>, T, ChannelType.Push> =
    this.map { it.asPush() }.thenJoin(label)

/**
 * Attaches a match node into the builder chain, which can then be continued after this call.
 *
 * When used in combination of other nodes, could construct (for example):
 * - within a bounded network -> entry gate that controls vehicle access into a capacity limited region of the port
 * - combined with service node -> ASC loading region, where port vehicles are loaded from containers provided elsewhere
 *   in the port
 *
 *     @param combiner Function to combine an instance of `MainInputT` with an instance of `SideInputT` for the node to
 *       generate an instance of `OutputT`
 */
fun <MainInputT, SideInputT, OutputT, ChannelT : ChannelType<ChannelT>> NodeBuilder<MainInputT, ChannelT>.thenMatch(
    label: String,
    side: NodeBuilder<SideInputT, ChannelType.Pull>,
    combiner: (MainInputT, SideInputT) -> OutputT,
): RegularNodeBuilder<MatchNode<MainInputT, SideInputT, OutputT, ChannelT>, OutputT, ChannelT> =
    zip(this.channelType, this, side) { inputA, inputB, output -> MatchNode(label, inputA, inputB, output, combiner) }

/**
 * Attaches a buffered queue (of limited max capacity) into the builder chain, which can then be continued after this
 * call. If a bounded queue reaches maximum capacity, the node will not accept anymore pushes, or will not pull from the
 * upstream node, until something has left the bounded queue
 *
 * Simulates a holding area / buffer, which when used with other nodes can construct:
 * - within a bounded subnetwork -> parking lot to store port vehicles while not in use
 * - combined with a fork node -> buffers or queues of vehicles waiting to pass through a gate or to be dispatched to a
 *   service node
 *
 * @param capacity Maximum capacity of the bounded queue instance.
 * @param policy Controls the behaviour of the queue, i.e., prioritising certain vehicles to exit the queue before
 *   others.
 */
fun <T> NodeBuilder<T, *>.thenBoundedQueue(
    label: String,
    capacity: Int,
    policy: QueuePolicy<T> = FIFOQueuePolicy(),
): RegularNodeBuilder<BoundedQueueNode<T>, T, ChannelType.Pull> =
    asPush().then(ChannelType.Pull) { input, output -> BoundedQueueNode(label, input, output, capacity, policy) }

/**
 * Attaches an unbuffered queue (infinite capacity) into the builder chain, which can then be continued after this call.
 *
 * Simulates a holding area / buffer, which when used with other nodes can construct:
 * - within a bounded subnetwork -> parking lot to store port vehicles while not in use
 * - combined with a fork node -> buffers or queues of vehicles waiting to pass through a gate or to be dispatched to a
 *   service node
 *
 * @param policy Controls the behaviour of the queue, i.e., prioritising certain vehicles to exit the queue before
 *   others.
 */
fun <T> NodeBuilder<T, *>.thenQueue(
    label: String,
    policy: QueuePolicy<T> = FIFOQueuePolicy(),
): RegularNodeBuilder<QueueNode<T>, T, ChannelType.Pull> =
    asPush().then(ChannelType.Pull) { input, output -> QueueNode(label, input, output, policy) }

/**
 * Attaches a service node into the builder chain, which can then be continued after this call.
 *
 * Simulates a service location that provides some delay, likely to be used in combination with other nodes. For
 * example:
 * - combined with a split node -> ASC unloading a port vehicle
 * - combined with a merge node -> ASC loading a port vehicle
 *
 * @param numServers Defines how many parallel servers are present in the service node. Doubling numServers functionally
 *   halves the delay of the service node
 */
fun <T> NodeBuilder<T, *>.thenService(
    label: String,
    delayProvider: DelayProvider,
    numServers: Int = 1,
): RegularNodeBuilder<ServiceNode<T>, T, ChannelType.Push> =
    asPush().then(ChannelType.Push) { input, output -> ServiceNode(label, input, output, delayProvider, numServers) }

/**
 * Attaches a split node into the builder chain. Then the different pathways for the splitter node outputs are defined.
 * Split node simulates a location where one item splits into two items, such as
 * - a booth for trucks to return a token when leaving an access controlled part of a port
 * - a crane that separates the container being carried by the port vehicle, and stores the container into storage
 *
 * @param splitter Function of how to split each InputT item.
 */
fun <InputT, MainOutputT, SideOutputT, ChannelT : ChannelType<ChannelT>> NodeBuilder<InputT, ChannelT>.thenSplit(
    label: String,
    splitter: (InputT) -> Pair<MainOutputT, SideOutputT>,
): Pair<
    RegularNodeBuilder<SplitNode<InputT, MainOutputT, SideOutputT, ChannelT>, MainOutputT, ChannelT>,
    RegularNodeBuilder<SplitNode<InputT, MainOutputT, SideOutputT, ChannelT>, SideOutputT, ChannelType.Push>,
> =
    thenUnzip(this.channelType, ChannelType.Push) { input, outputA, outputB ->
        SplitNode(label, input, outputA, outputB, splitter)
    }

/** Attaches a sink and terminates the builder chain. */
fun <T> NodeBuilder<T, *>.thenSink(label: String): SinkNode<T> =
    asPush().thenTerminal { input -> SinkNode(label, input) }

/**
 * Attaches a loss sink, a special loss node that is hidden from certain metrics, to be used to simulate loss / dropped
 * items
 */
fun <T> NodeBuilder<T, *>.thenLossSink(label: String): LossSinkNode<T> =
    asPush().thenTerminal { input -> LossSinkNode(label, input) }

/**
 * Attaches a dead end node and terminates the builder chain. This represents a node whose push input channel is always
 * closed, or never pulls.
 */
fun <T> NodeBuilder<T, *>.thenDeadEnd(label: String): DeadEndNode<T> = thenTerminal { input ->
    DeadEndNode(label, input)
}

/**
 * Converts the builder chain from push / pull-out, to push-out, such that a push-in node can be connected to the
 * builder chain.
 */
private fun <T> NodeBuilder<T, *>.asPush(): NodeBuilder<T, ChannelType.Push> =
    if (this.isPush()) {
        this
    } else {
        this.thenPump()
    }

/**
 * Returns whether the type of the output connection of the previous node in the builder chain, is a push-output or not.
 */
@Suppress("KotlinConstantConditions")
private fun <T> NodeBuilder<T, *>.isPush(): Boolean {
    contract {
        returns(true) implies (this@isPush is NodeBuilder<T, ChannelType.Push>)
        returns(false) implies (this@isPush is NodeBuilder<T, ChannelType.Pull>)
    }
    return channelType == ChannelType.Push
}
