package com.group7.dsl

import com.group7.*
import com.group7.channels.*
import com.group7.tags.BasicTag
import com.group7.tags.MutableBasicTag
import com.group7.tags.newTag
import kotlin.contracts.InvocationKind
import kotlin.contracts.contract

/** Interface for objects that can be built upon by the DSL functions. */
sealed interface NodeBuilder<out ItemT, ChannelT : ChannelType<ChannelT>> {
    val channelType: ChannelT
}

/**
 * NodeBuilder following on immediately from a node in the chain, usually representing the traditional left-right flow
 * of nodes in the queue network
 */
sealed interface RegularNodeBuilder<out NodeT : NodeGroup, ItemT, ChannelT : ChannelType<ChannelT>> :
    NodeBuilder<ItemT, ChannelT> {
    val node: NodeT
}

/**
 * NodeBuilder joining two non-adjacent parts of a queue network, or spanning two otherwise separate queue networks,
 * together.
 */
sealed interface Connection<ItemT, ChannelT : ChannelType<ChannelT>> : NodeBuilder<ItemT, ChannelT>

internal val <ItemT, ChannelT : ChannelType<ChannelT>> Connection<ItemT, ChannelT>.nextInput
    get() = asImpl().nextInput

/** Creates a new connection generic of whether it will be push or pull */
fun <ItemT, ChannelT : ChannelType<ChannelT>> newConnection(channelType: ChannelT): Connection<ItemT, ChannelT> =
    ConnectionImpl(channelType)

/** Creates a new push [Connection] */
fun <ItemT> newPushConnection(): Connection<ItemT, ChannelType.Push> = newConnection(ChannelType.Push)

/** Creates a new pull [Connection] */
fun <ItemT> newPullConnection(): Connection<ItemT, ChannelType.Pull> = newConnection(ChannelType.Pull)

/** A reference to an output channel, which can then be connected to other nodes directly */
sealed interface OutputRef<ItemT, ChannelT : ChannelType<ChannelT>> {
    val output: OutputChannel<ItemT, ChannelT>
}

/** Internal implementation of the node DSL builder */
private class NodeBuilderImpl<out NodeT : NodeGroup, ItemT, OutputChannelT : ChannelType<OutputChannelT>>(
    override val node: NodeT,
    val output: ConnectableOutputChannel<ItemT, OutputChannelT>,
) : RegularNodeBuilder<NodeT, ItemT, OutputChannelT> {
    @Suppress("UNCHECKED_CAST")
    override val channelType
        get() = (if (output.isPush()) ChannelType.Push else ChannelType.Pull) as OutputChannelT
}

/** Internal implementation of a generic [Connection] */
internal class ConnectionImpl<ItemT, ChannelT : ChannelType<ChannelT>>(override val channelType: ChannelT) :
    Connection<ItemT, ChannelT> {
    val nextInput = newConnectableInputChannel<ItemT, _>(channelType)
}

/** Internal representation of an [OutputRef] */
private class OutputRefImpl<ItemT, ChannelT : ChannelType<ChannelT>> : OutputRef<ItemT, ChannelT> {
    override lateinit var output: ConnectableOutputChannel<ItemT, ChannelT>
}

/**
 * Initiates the DSL builder chain through constructing a [NodeBuilderImpl] to be passed around and added to by the
 * subsequent DSL chain.
 *
 * @param NodeT Type of the node to start the DSL chain. Should be a source node
 * @param OutputT Type of vehicle / item generated by the source `NodeT`
 * @param outputChannelType Type of output channel to connect the `node` to, and thus the type of in-channel for the
 *   next node in the DSL chain.
 * @param node Lambda function to create an instance of the starting node, whose output is connected to the
 *   [OutputChannel] supplied as argument.
 */
context(scenarioScope: ScenarioBuilderScope)
internal fun <NodeT : SourceNode, OutputT, OutputChannelT : ChannelType<OutputChannelT>> sourceBuilder(
    outputChannelType: OutputChannelT,
    node: (OutputChannel<OutputT, OutputChannelT>) -> NodeT,
): RegularNodeBuilder<NodeT, OutputT, OutputChannelT> {
    val output = newConnectableOutputChannel<OutputT, _>(outputChannelType)
    val source = node(output)
    scenarioScope.asImpl().sources.add(source)
    return NodeBuilderImpl(source, output)
}

/**
 * Attaches the provided node and associated information to the builder chain passed around.
 *
 * @param NodeT The type of `node` to be added to the chain
 * @param InputT The type of vehicle / object to be inputted into `node`
 * @param OutputT The type of vehicle / object outputted by `node` to the next node of the builder chain
 * @param InputChannelT The type of channel (push / pull, upper bound by [ChannelType]) `node` takes
 * @param outputChannelType The type of channel (push / pull, upper bound by [ChannelType]) `node` will generate
 * @param node Node to attach onto the NodeBuilder chain.
 */
internal fun <
    NodeT : NodeGroup,
    InputT,
    OutputT,
    InputChannelT : ChannelType<InputChannelT>,
    OutputChannelT : ChannelType<OutputChannelT>,
> NodeBuilder<InputT, InputChannelT>.then(
    outputChannelType: OutputChannelT,
    node: (InputChannel<InputT, InputChannelT>, OutputChannel<OutputT, OutputChannelT>) -> NodeT,
): RegularNodeBuilder<NodeT, OutputT, OutputChannelT> {
    val input = nextInput(this.channelType)
    val output = newConnectableOutputChannel<OutputT, _>(outputChannelType)
    return NodeBuilderImpl(node(input, output), output)
}

internal fun <
    NodeT : NodeGroup,
    InputT,
    OutputT,
    InputChannelT : ChannelType<InputChannelT>,
    OutputChannelT : ChannelType<OutputChannelT>,
> NodeBuilder<InputT, InputChannelT>.thenDiverge(
    outputChannelType: OutputChannelT,
    numLanes: Int,
    node: (InputChannel<InputT, InputChannelT>, List<OutputChannel<OutputT, OutputChannelT>>) -> NodeT,
): List<RegularNodeBuilder<NodeT, OutputT, OutputChannelT>> {
    val input = nextInput(this.channelType)
    val outputs = List(numLanes) { newConnectableOutputChannel<OutputT, _>(outputChannelType) }
    val forkNode = node(input, outputs)
    return outputs.map { NodeBuilderImpl(forkNode, it) }
}

internal fun <
    NodeT : NodeGroup,
    InputT,
    OutputT,
    InputChannelT : ChannelType<InputChannelT>,
    OutputChannelT : ChannelType<OutputChannelT>,
> List<NodeBuilder<InputT, InputChannelT>>.thenConverge(
    outputChannelType: OutputChannelT,
    node: (List<InputChannel<InputT, InputChannelT>>, OutputChannel<OutputT, OutputChannelT>) -> NodeT,
): RegularNodeBuilder<NodeT, OutputT, OutputChannelT> {
    val inputs = this.map { it.nextInput(it.channelType) }
    val output = newConnectableOutputChannel<OutputT, _>(outputChannelType)

    return NodeBuilderImpl(node(inputs, output), output)
}

/**
 * Runs `saver` with the immediately prior node in the builder chain, and allows the builder chain to continue after
 * this function.
 *
 * @param saver Lambda function provided the immediate prior node to be saved or have some computation done to
 */
inline fun <BuilderT : RegularNodeBuilder<NodeT, *, *>, NodeT : NodeGroup> BuilderT.saveNode(
    saver: (NodeT) -> Unit
): BuilderT {
    contract { callsInPlace(saver, InvocationKind.EXACTLY_ONCE) }
    return also { saver(it.node) }
}

internal fun <
    NodeT : NodeGroup,
    InputAT,
    InputBT,
    OutputT,
    InputAChannelT : ChannelType<InputAChannelT>,
    InputBChannelT : ChannelType<InputBChannelT>,
    OutputChannelT : ChannelType<OutputChannelT>,
> zip(
    outputChannelType: OutputChannelT,
    a: NodeBuilder<InputAT, InputAChannelT>,
    b: NodeBuilder<InputBT, InputBChannelT>,
    node:
        (
            InputChannel<InputAT, InputAChannelT>,
            InputChannel<InputBT, InputBChannelT>,
            OutputChannel<OutputT, OutputChannelT>,
        ) -> NodeT,
): RegularNodeBuilder<NodeT, OutputT, OutputChannelT> {
    val inputA = a.nextInput(a.channelType)
    val inputB = b.nextInput(b.channelType)
    val output = newConnectableOutputChannel<OutputT, _>(outputChannelType)
    return NodeBuilderImpl(node(inputA, inputB, output), output)
}

internal fun <
    NodeT : NodeGroup,
    InputT,
    OutputAT,
    OutputBT,
    InputChannelT : ChannelType<InputChannelT>,
    OutputAChannelT : ChannelType<OutputAChannelT>,
    OutputBChannelT : ChannelType<OutputBChannelT>,
> NodeBuilder<InputT, InputChannelT>.thenUnzip(
    outputAChannelType: OutputAChannelT,
    outputBChannelType: OutputBChannelT,
    node:
        (
            InputChannel<InputT, InputChannelT>,
            OutputChannel<OutputAT, OutputAChannelT>,
            OutputChannel<OutputBT, OutputBChannelT>,
        ) -> NodeT,
): Pair<RegularNodeBuilder<NodeT, OutputAT, OutputAChannelT>, RegularNodeBuilder<NodeT, OutputBT, OutputBChannelT>> {
    val input = nextInput(this.channelType)
    val outputA = newConnectableOutputChannel<OutputAT, _>(outputAChannelType)
    val outputB = newConnectableOutputChannel<OutputBT, _>(outputBChannelType)
    val zipNode = node(input, outputA, outputB)
    return Pair(NodeBuilderImpl(zipNode, outputA), NodeBuilderImpl(zipNode, outputB))
}

internal fun <NodeT : NodeGroup, InputT, InputChannelT : ChannelType<InputChannelT>> NodeBuilder<InputT, InputChannelT>
    .thenTerminal(node: (InputChannel<InputT, InputChannelT>) -> NodeT): NodeT {
    val input = nextInput(this.channelType)
    return node(input)
}

internal fun <
    NodeT : NodeGroup,
    InputT,
    OutputT,
    InputChannelT : ChannelType<InputChannelT>,
    OutputChannelT : ChannelType<OutputChannelT>,
> NodeBuilder<InputT, InputChannelT>.thenCompound(
    node: (Connection<out InputT, InputChannelT>, OutputRef<OutputT, OutputChannelT>) -> NodeT
): RegularNodeBuilder<NodeT, OutputT, OutputChannelT> {
    val connection =
        this.patternMatch(
            whenConnection = { it },
            whenRegular = { builder ->
                newConnection<InputT, InputChannelT>(this.channelType).also { builder.thenConnect(it) }
            },
        )
    val output = OutputRefImpl<OutputT, OutputChannelT>()
    // Preserve the current group scope when the node constructor finishes or throws
    val compoundNode = GroupScope.withGroup(GroupScope.current) { node(connection, output) }
    return NodeBuilderImpl(compoundNode, output.output)
}

fun <ItemT, ChannelT : ChannelType<ChannelT>> RegularNodeBuilder<*, out ItemT, ChannelT>.thenConnect(
    connection: Connection<in ItemT, ChannelT>
) {
    this.asImpl().output.connectTo(connection.asImpl().nextInput)
}

fun <ItemT, ChannelT : ChannelType<ChannelT>> RegularNodeBuilder<*, ItemT, ChannelT>.thenOutput(
    outputRef: OutputRef<ItemT, ChannelT>
) {
    outputRef.asImpl().output = this.asImpl().output
}

fun <BuilderT : RegularNodeBuilder<NodeT, *, *>, NodeT : NodeGroup> BuilderT.tagged(
    tag: MutableBasicTag<in NodeT>
): BuilderT {
    tag.bind(this.node)
    return this
}

fun <BuilderT : RegularNodeBuilder<NodeT, *, *>, NodeT : NodeGroup> BuilderT.tagged(
    tags: MutableList<in BasicTag<NodeT>>
): BuilderT {
    tags.add(newTag(this.node))
    return this
}

private fun <T, ChannelT : ChannelType<ChannelT>> NodeBuilder<T, ChannelT>.nextInput(
    channelType: ChannelT
): InputChannel<T, ChannelT> =
    this.patternMatch(
        whenConnection = { it.nextInput },
        whenRegular = { builder ->
            newConnectableInputChannel<T, _>(channelType).also { builder.asImpl().output.connectTo(it) }
        },
    )

private fun <NodeT : NodeGroup, ItemT, ChannelT : ChannelType<ChannelT>> RegularNodeBuilder<NodeT, ItemT, ChannelT>
    .asImpl(): NodeBuilderImpl<NodeT, ItemT, ChannelT> =
    when (this) {
        is NodeBuilderImpl -> this
    }

private fun <ItemT, ChannelT : ChannelType<ChannelT>> Connection<ItemT, ChannelT>.asImpl():
    ConnectionImpl<ItemT, ChannelT> =
    when (this) {
        is ConnectionImpl -> this
    }

private fun <ItemT, ChannelT : ChannelType<ChannelT>> OutputRef<ItemT, ChannelT>.asImpl():
    OutputRefImpl<ItemT, ChannelT> =
    when (this) {
        is OutputRefImpl -> this
    }

private inline fun <ItemT, ChannelT : ChannelType<ChannelT>, R> NodeBuilder<ItemT, ChannelT>.patternMatch(
    whenRegular: (RegularNodeBuilder<*, out ItemT, ChannelT>) -> R,
    whenConnection: (Connection<out ItemT, ChannelT>) -> R,
): R {
    contract {
        callsInPlace(whenRegular, InvocationKind.AT_MOST_ONCE)
        callsInPlace(whenConnection, InvocationKind.AT_MOST_ONCE)
    }
    return when (this) {
        is NodeBuilderImpl<*, out ItemT, ChannelT> -> whenRegular(this)
        is ConnectionImpl -> whenConnection(this)
    }
}
