package com.group7.dsl

import com.group7.*
import com.group7.channels.*
import com.group7.tags.BasicTag
import com.group7.tags.MutableBasicTag
import com.group7.tags.newTag
import kotlin.contracts.InvocationKind
import kotlin.contracts.contract

/** Interface for objects that can be built upon by the DSL functions. */
sealed interface NodeBuilder<out ItemT, ChannelT : ChannelType<ChannelT>> {
    val channelType: ChannelT
}

/**
 * NodeBuilder following on immediately from a node in the chain, usually representing the traditional left-right flow
 * of nodes in the queue network
 */
sealed interface RegularNodeBuilder<out NodeT : NodeGroup, ItemT, ChannelT : ChannelType<ChannelT>> :
    NodeBuilder<ItemT, ChannelT> {
    val node: NodeT
}

/**
 * NodeBuilder joining two non-adjacent parts of a queue network, or spanning two otherwise separate queue networks,
 * together.
 */
sealed interface Connection<ItemT, ChannelT : ChannelType<ChannelT>> : NodeBuilder<ItemT, ChannelT>

internal val <ItemT, ChannelT : ChannelType<ChannelT>> Connection<ItemT, ChannelT>.nextInput
    get() = asImpl().nextInput

/** Creates a new connection generic of whether it will be push or pull */
fun <ItemT, ChannelT : ChannelType<ChannelT>> newConnection(channelType: ChannelT): Connection<ItemT, ChannelT> =
    ConnectionImpl(channelType)

/** Creates a new push [Connection] */
fun <ItemT> newPushConnection(): Connection<ItemT, ChannelType.Push> = newConnection(ChannelType.Push)

/** Creates a new pull [Connection] */
fun <ItemT> newPullConnection(): Connection<ItemT, ChannelType.Pull> = newConnection(ChannelType.Pull)

/** A reference to an output channel, which can then be connected to other nodes directly */
sealed interface OutputRef<ItemT, ChannelT : ChannelType<ChannelT>> {
    val output: OutputChannel<ItemT, ChannelT>
}

/** Internal implementation of the node DSL builder */
private class NodeBuilderImpl<out NodeT : NodeGroup, ItemT, OutputChannelT : ChannelType<OutputChannelT>>(
    override val node: NodeT,
    val output: ConnectableOutputChannel<ItemT, OutputChannelT>,
) : RegularNodeBuilder<NodeT, ItemT, OutputChannelT> {
    @Suppress("UNCHECKED_CAST")
    override val channelType
        get() = (if (output.isPush()) ChannelType.Push else ChannelType.Pull) as OutputChannelT
}

/** Internal implementation of a generic [Connection] */
internal class ConnectionImpl<ItemT, ChannelT : ChannelType<ChannelT>>(override val channelType: ChannelT) :
    Connection<ItemT, ChannelT> {
    val nextInput = newConnectableInputChannel<ItemT, _>(channelType)
}

/** Internal representation of an [OutputRef] */
private class OutputRefImpl<ItemT, ChannelT : ChannelType<ChannelT>> : OutputRef<ItemT, ChannelT> {
    override lateinit var output: ConnectableOutputChannel<ItemT, ChannelT>
}

/**
 * Initiates the DSL builder chain through constructing a [NodeBuilderImpl] to be passed around and added to by the
 * subsequent DSL chain.
 *
 * @param NodeT Type of the node to start the DSL chain. Should be a source node
 * @param OutputT Type of vehicle / item generated by the source `NodeT`
 * @param outputChannelType Type of output channel to connect the node to, and thus the type of in-channel for the next
 *   node in the DSL chain.
 * @param node Lambda function to create an instance of the starting node.
 */
context(scenarioScope: ScenarioBuilderScope)
internal fun <NodeT : SourceNode, OutputT, OutputChannelT : ChannelType<OutputChannelT>> sourceBuilder(
    outputChannelType: OutputChannelT,
    node: (OutputChannel<OutputT, OutputChannelT>) -> NodeT,
): RegularNodeBuilder<NodeT, OutputT, OutputChannelT> {
    val output = newConnectableOutputChannel<OutputT, _>(outputChannelType)
    val source = node(output)
    scenarioScope.asImpl().sources.add(source)
    return NodeBuilderImpl(source, output)
}

/**
 * Attaches the provided node and associated information to the builder chain passed around.
 *
 * @param NodeT The type of node to be added to the chain
 * @param InputT The type of vehicle / object to be inputted into node
 * @param OutputT The type of vehicle / object outputted by node to the next node of the builder chain
 * @param InputChannelT The type of channel (push / pull, upper bound by [ChannelType]) node takes
 * @param outputChannelType The type of channel (push / pull, upper bound by [ChannelType]) node will generate
 * @param node Lambda function to create an instance of the node.
 */
internal fun <
    NodeT : NodeGroup,
    InputT,
    OutputT,
    InputChannelT : ChannelType<InputChannelT>,
    OutputChannelT : ChannelType<OutputChannelT>,
> NodeBuilder<InputT, InputChannelT>.then(
    outputChannelType: OutputChannelT,
    node: (InputChannel<InputT, InputChannelT>, OutputChannel<OutputT, OutputChannelT>) -> NodeT,
): RegularNodeBuilder<NodeT, OutputT, OutputChannelT> {
    val input = nextInput(this.channelType)
    val output = newConnectableOutputChannel<OutputT, _>(outputChannelType)
    return NodeBuilderImpl(node(input, output), output)
}

/**
 * Generates a set of output channels, and connects the NodeBuilder to the nodes' output, which can then be used to
 * define the parallel lanes from
 *
 * @param NodeT The type of diverging node to be added to the builder chain
 * @param InputT The type of object to be inputted into node
 * @param OutputT The type of object that is emitted by node into the lanes
 * @param InputChannelT The type of channel (push / pull, upper bound by [ChannelType]) node takes
 * @param outputChannelType The type of channel (push / pull, upper bound by [ChannelType]) node will generate
 * @param numLanes Number of lanes to generate output channels for
 * @param node Lambda function to create an instance of the node.
 */
internal fun <
    NodeT : NodeGroup,
    InputT,
    OutputT,
    InputChannelT : ChannelType<InputChannelT>,
    OutputChannelT : ChannelType<OutputChannelT>,
> NodeBuilder<InputT, InputChannelT>.thenDiverge(
    outputChannelType: OutputChannelT,
    numLanes: Int,
    node: (InputChannel<InputT, InputChannelT>, List<OutputChannel<OutputT, OutputChannelT>>) -> NodeT,
): List<RegularNodeBuilder<NodeT, OutputT, OutputChannelT>> {
    val input = nextInput(this.channelType)
    val outputs = List(numLanes) { newConnectableOutputChannel<OutputT, _>(outputChannelType) }
    val forkNode = node(input, outputs)
    return outputs.map { NodeBuilderImpl(forkNode, it) }
}

/**
 * Converges the input channels supplied by the NodeBuilders as input, and converges them to one NodeBuilder via.
 * creating an instance of the node.
 *
 * @param NodeT The type of converging node to be added to the builder chain
 * @param InputT The type of object to be inputted into node
 * @param OutputT The type of object that is emitted by node into the lanes
 * @param InputChannelT The type of channel (push / pull, upper bound by [ChannelType]) node takes
 * @param outputChannelType The type of channel (push / pull, upper bound by [ChannelType]) node will generate
 * @param node Lambda function to create an instance of the starting node.
 */
internal fun <
    NodeT : NodeGroup,
    InputT,
    OutputT,
    InputChannelT : ChannelType<InputChannelT>,
    OutputChannelT : ChannelType<OutputChannelT>,
> List<NodeBuilder<InputT, InputChannelT>>.thenConverge(
    outputChannelType: OutputChannelT,
    node: (List<InputChannel<InputT, InputChannelT>>, OutputChannel<OutputT, OutputChannelT>) -> NodeT,
): RegularNodeBuilder<NodeT, OutputT, OutputChannelT> {
    val inputs = this.map { it.nextInput(it.channelType) }
    val output = newConnectableOutputChannel<OutputT, _>(outputChannelType)

    return NodeBuilderImpl(node(inputs, output), output)
}

/**
 * Runs `saver` to the immediately prior node inline in the builder chain, and allows the builder chain to continue
 * after this function.
 *
 * @param saver Lambda function provided the immediate prior node to be saved or have some computation done to
 */
inline fun <BuilderT : RegularNodeBuilder<NodeT, *, *>, NodeT : NodeGroup> BuilderT.saveNode(
    saver: (NodeT) -> Unit
): BuilderT {
    contract { callsInPlace(saver, InvocationKind.EXACTLY_ONCE) }
    return also { saver(it.node) }
}

/**
 * Connects two builder chains with different object types through a converging node that performs some computation to
 * convert the objects to another type
 *
 * @param NodeT The type of zipping node (or node group) to be added into the builder chain
 * @param InputAT Type of object builder chain `a` processes
 * @param InputBT Type of object builder chain `b` processes
 * @param OutputT Type of object the zipping node produces
 * @param InputAChannelT Type of channel builder chain `a` provides to this node
 * @param InputBChannelT Type of channel builder chain `b` provides to this node
 * @param outputChannelType The type of channel (push / pull, upper bound by [ChannelType]) node will generate
 * @param a NodeBuilder to be merged into
 * @param b NodeBuilder merging into `a`
 * @param node Lambda function to generate the zipping node group
 */
internal fun <
    NodeT : NodeGroup,
    InputAT,
    InputBT,
    OutputT,
    InputAChannelT : ChannelType<InputAChannelT>,
    InputBChannelT : ChannelType<InputBChannelT>,
    OutputChannelT : ChannelType<OutputChannelT>,
> zip(
    outputChannelType: OutputChannelT,
    a: NodeBuilder<InputAT, InputAChannelT>,
    b: NodeBuilder<InputBT, InputBChannelT>,
    node:
        (
            InputChannel<InputAT, InputAChannelT>,
            InputChannel<InputBT, InputBChannelT>,
            OutputChannel<OutputT, OutputChannelT>,
        ) -> NodeT,
): RegularNodeBuilder<NodeT, OutputT, OutputChannelT> {
    val inputA = a.nextInput(a.channelType)
    val inputB = b.nextInput(b.channelType)
    val output = newConnectableOutputChannel<OutputT, _>(outputChannelType)
    return NodeBuilderImpl(node(inputA, inputB, output), output)
}

/**
 * The inverse of the `.thenZip` function. Takes instances of objects travelling through the current NodeBuilder chain,
 * and splits them up using the splitting `node` provided.
 *
 * @param NodeT The type of splitting node (or node group) to be added into the builder chain
 * @param InputT Type of object the current builder chain processes
 * @param OutputAT Type of the first object generated by the splitter node
 * @param OutputBT Type of the second object generated by the splitter node
 * @param InputChannelT Type of channel the current NodeBuilder provides, and will be attached to the node provided
 * @param outputAChannelType Type of channel the split builder chain OutputA will be provided
 * @param outputBChannelType Type of channel the split builder chain OutputB will be provided
 * @param node Lambda function to generate the splitting node group
 */
internal fun <
    NodeT : NodeGroup,
    InputT,
    OutputAT,
    OutputBT,
    InputChannelT : ChannelType<InputChannelT>,
    OutputAChannelT : ChannelType<OutputAChannelT>,
    OutputBChannelT : ChannelType<OutputBChannelT>,
> NodeBuilder<InputT, InputChannelT>.thenUnzip(
    outputAChannelType: OutputAChannelT,
    outputBChannelType: OutputBChannelT,
    node:
        (
            InputChannel<InputT, InputChannelT>,
            OutputChannel<OutputAT, OutputAChannelT>,
            OutputChannel<OutputBT, OutputBChannelT>,
        ) -> NodeT,
): Pair<RegularNodeBuilder<NodeT, OutputAT, OutputAChannelT>, RegularNodeBuilder<NodeT, OutputBT, OutputBChannelT>> {
    val input = nextInput(this.channelType)
    val outputA = newConnectableOutputChannel<OutputAT, _>(outputAChannelType)
    val outputB = newConnectableOutputChannel<OutputBT, _>(outputBChannelType)
    val zipNode = node(input, outputA, outputB)
    return Pair(NodeBuilderImpl(zipNode, outputA), NodeBuilderImpl(zipNode, outputB))
}

/**
 * Terminates the builder chain, and returns the node generated.
 *
 * @param NodeT Type of terminating node to add
 * @param InputT Type of object the current builder chain processes, and will be passed to the node
 * @param InputChannelT Type of channel the current NodeBuilder provides, and will be attached to the node provided
 * @param node Lambda function to generate the zipping node group
 */
internal fun <NodeT : NodeGroup, InputT, InputChannelT : ChannelType<InputChannelT>> NodeBuilder<InputT, InputChannelT>
    .thenTerminal(node: (InputChannel<InputT, InputChannelT>) -> NodeT): NodeT {
    val input = nextInput(this.channelType)
    return node(input)
}

/**
 * Attaches a compound node to the current NodeBuilder through generating and attaching the sufficient connections.
 *
 * @param NodeT Type of compound node to add
 * @param InputT Type of object the current builder chain processes, and will be passed to the node
 * @param OutputT Type of object the node produces, and will be passed to the next node in the builder chain.
 * @param InputChannelT Type of channel provided by the current NodeBuilder
 * @param OutputChannelT Type of channel provided by the node, and will be supplied to the next node in the NodeBuilder
 *   chain
 * @param node Lambda function to generate the compound node.
 */
internal fun <
    NodeT : NodeGroup,
    InputT,
    OutputT,
    InputChannelT : ChannelType<InputChannelT>,
    OutputChannelT : ChannelType<OutputChannelT>,
> NodeBuilder<InputT, InputChannelT>.thenCompound(
    node: (Connection<out InputT, InputChannelT>, OutputRef<OutputT, OutputChannelT>) -> NodeT
): RegularNodeBuilder<NodeT, OutputT, OutputChannelT> {
    // Create connection to provide to `node` as input to join NB output to node input
    val connection =
        this.patternMatch(
            whenConnection = { it },
            whenRegular = { builder ->
                newConnection<InputT, InputChannelT>(this.channelType).also { builder.thenConnect(it) }
            },
        )
    val output = OutputRefImpl<OutputT, OutputChannelT>()
    // Preserve the current group scope when the node constructor finishes or throws
    val compoundNode = GroupScope.withGroup(GroupScope.current) { node(connection, output) }
    return NodeBuilderImpl(compoundNode, output.output)
}

/**
 * Ends the current NodeBuilder chain, and all objects processed by the nodes in the chain will be fed to the opposite
 * end of the connection supplied.
 *
 * The NodeBuilder does not continue past this point.
 *
 * @param ItemT Type of object processed by this NodeBuilder
 * @param ChannelT Type of channel provided by the current NodeBuilder
 * @param connection Connection to connect the NodeBuilder's output to
 */
fun <ItemT, ChannelT : ChannelType<ChannelT>> RegularNodeBuilder<*, out ItemT, ChannelT>.thenConnect(
    connection: Connection<in ItemT, ChannelT>
) {
    this.asImpl().output.connectTo(connection.asImpl().nextInput)
}

/**
 * Ends the current NodeBuilder chain, and all objects processed by the nodes in the chain will be fed to the
 * destination of the OutputRef provided. For compound node, `outputRef` connects the internal output of the builder
 * chain to the output of the compound node in the main flow
 *
 * The NodeBuidler does not continue past this point.
 *
 * @param ItemT Type of object provided by this NodeBuilder
 * @param ChannelT Type of channel [OutputRef] will take
 * @param outputRef [OutputRef] supplied earlier to connect the NodeBuilder's output to.
 */
fun <ItemT, ChannelT : ChannelType<ChannelT>> RegularNodeBuilder<*, ItemT, ChannelT>.thenOutput(
    outputRef: OutputRef<ItemT, ChannelT>
) {
    outputRef.asImpl().output = this.asImpl().output
}

/** Tags the immediate previous node in the builder chain with the tag supplied. */
fun <BuilderT : RegularNodeBuilder<NodeT, *, *>, NodeT : NodeGroup> BuilderT.tagged(
    tag: MutableBasicTag<in NodeT>
): BuilderT {
    tag.bind(this.node)
    return this
}

/**
 * Adds to the list of tags, a tag for the immediate previous node in the builder chain.
 *
 * @param tags List of tags to add to
 */
fun <BuilderT : RegularNodeBuilder<NodeT, *, *>, NodeT : NodeGroup> BuilderT.tagged(
    tags: MutableList<in BasicTag<NodeT>>
): BuilderT {
    tags.add(newTag(this.node))
    return this
}

/**
 * Generates the next [InputChannel] to use in the builder chain, and connects it with the previous node (if applicable)
 *
 * @param channelType Type of channel the NodeBuilder supplies, and will be provided to the next node.
 */
private fun <T, ChannelT : ChannelType<ChannelT>> NodeBuilder<T, ChannelT>.nextInput(
    channelType: ChannelT
): InputChannel<T, ChannelT> =
    this.patternMatch(
        whenConnection = { it.nextInput },
        whenRegular = { builder ->
            newConnectableInputChannel<T, _>(channelType).also { builder.asImpl().output.connectTo(it) }
        },
    )

/** Exposes internals of [NodeBuilder]. */
private fun <NodeT : NodeGroup, ItemT, ChannelT : ChannelType<ChannelT>> RegularNodeBuilder<NodeT, ItemT, ChannelT>
    .asImpl(): NodeBuilderImpl<NodeT, ItemT, ChannelT> =
    when (this) {
        is NodeBuilderImpl -> this
    }

/** Exposes internals of [Connection]. */
private fun <ItemT, ChannelT : ChannelType<ChannelT>> Connection<ItemT, ChannelT>.asImpl():
    ConnectionImpl<ItemT, ChannelT> =
    when (this) {
        is ConnectionImpl -> this
    }

/** Exposes internals of [OutputRef] */
private fun <ItemT, ChannelT : ChannelType<ChannelT>> OutputRef<ItemT, ChannelT>.asImpl():
    OutputRefImpl<ItemT, ChannelT> =
    when (this) {
        is OutputRefImpl -> this
    }

/**
 * Patterns match and executes the appropriate provided lambda functions on the type of NodeBuilder
 *
 * @param whenRegular Lambda function to call if NodeBuilder internally is an instance of [NodeBuilderImpl]
 * @param whenConnection Lambda function to call if NodeBuilder internally is an instance of [ConnectionImpl]
 */
private inline fun <ItemT, ChannelT : ChannelType<ChannelT>, R> NodeBuilder<ItemT, ChannelT>.patternMatch(
    whenRegular: (RegularNodeBuilder<*, out ItemT, ChannelT>) -> R,
    whenConnection: (Connection<out ItemT, ChannelT>) -> R,
): R {
    contract {
        callsInPlace(whenRegular, InvocationKind.AT_MOST_ONCE)
        callsInPlace(whenConnection, InvocationKind.AT_MOST_ONCE)
    }
    return when (this) {
        is NodeBuilderImpl<*, out ItemT, ChannelT> -> whenRegular(this)
        is ConnectionImpl -> whenConnection(this)
    }
}
